version: v3

networks:
  jenkins:

volumes:
  jenkins-vol:

services:
  jenkins-setup:
    container_name: jenkins-container1
    image: jenkins/jenkins
    volumes:
      - ./:/var/jenkins_home
      - jenkins-vol:/var/jenkins_home
    networks:
      - jenkins
    ports:
      - 8081:8080
      - 50000:50000
    expose:
      - 8081
    stdin_open: true
    restart: "always"